url: "https://briancoia.com"

permalink: pretty
template_engine: liquid

# base_path: "/" # the subpath of your site, e.g. /blog. If you set this option,
# ensure you use the `relative_url` helper for all links and assets in your HTML.
# If you're using esbuild for frontend assets, edit `esbuild.config.js` to
# update `publicPath`.

# timezone: America/Los_Angeles
# pagination:
#   enabled: true
